require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InventoryPartsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # InventoryPart. As you add validations to InventoryPart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InventoryPartsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all inventory_parts as @inventory_parts" do
      inventory_part = InventoryPart.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:inventory_parts)).to eq([inventory_part])
    end
  end

  describe "GET #show" do
    it "assigns the requested inventory_part as @inventory_part" do
      inventory_part = InventoryPart.create! valid_attributes
      get :show, {:id => inventory_part.to_param}, valid_session
      expect(assigns(:inventory_part)).to eq(inventory_part)
    end
  end

  describe "GET #new" do
    it "assigns a new inventory_part as @inventory_part" do
      get :new, {}, valid_session
      expect(assigns(:inventory_part)).to be_a_new(InventoryPart)
    end
  end

  describe "GET #edit" do
    it "assigns the requested inventory_part as @inventory_part" do
      inventory_part = InventoryPart.create! valid_attributes
      get :edit, {:id => inventory_part.to_param}, valid_session
      expect(assigns(:inventory_part)).to eq(inventory_part)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new InventoryPart" do
        expect {
          post :create, {:inventory_part => valid_attributes}, valid_session
        }.to change(InventoryPart, :count).by(1)
      end

      it "assigns a newly created inventory_part as @inventory_part" do
        post :create, {:inventory_part => valid_attributes}, valid_session
        expect(assigns(:inventory_part)).to be_a(InventoryPart)
        expect(assigns(:inventory_part)).to be_persisted
      end

      it "redirects to the created inventory_part" do
        post :create, {:inventory_part => valid_attributes}, valid_session
        expect(response).to redirect_to(InventoryPart.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved inventory_part as @inventory_part" do
        post :create, {:inventory_part => invalid_attributes}, valid_session
        expect(assigns(:inventory_part)).to be_a_new(InventoryPart)
      end

      it "re-renders the 'new' template" do
        post :create, {:inventory_part => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested inventory_part" do
        inventory_part = InventoryPart.create! valid_attributes
        put :update, {:id => inventory_part.to_param, :inventory_part => new_attributes}, valid_session
        inventory_part.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested inventory_part as @inventory_part" do
        inventory_part = InventoryPart.create! valid_attributes
        put :update, {:id => inventory_part.to_param, :inventory_part => valid_attributes}, valid_session
        expect(assigns(:inventory_part)).to eq(inventory_part)
      end

      it "redirects to the inventory_part" do
        inventory_part = InventoryPart.create! valid_attributes
        put :update, {:id => inventory_part.to_param, :inventory_part => valid_attributes}, valid_session
        expect(response).to redirect_to(inventory_part)
      end
    end

    context "with invalid params" do
      it "assigns the inventory_part as @inventory_part" do
        inventory_part = InventoryPart.create! valid_attributes
        put :update, {:id => inventory_part.to_param, :inventory_part => invalid_attributes}, valid_session
        expect(assigns(:inventory_part)).to eq(inventory_part)
      end

      it "re-renders the 'edit' template" do
        inventory_part = InventoryPart.create! valid_attributes
        put :update, {:id => inventory_part.to_param, :inventory_part => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested inventory_part" do
      inventory_part = InventoryPart.create! valid_attributes
      expect {
        delete :destroy, {:id => inventory_part.to_param}, valid_session
      }.to change(InventoryPart, :count).by(-1)
    end

    it "redirects to the inventory_parts list" do
      inventory_part = InventoryPart.create! valid_attributes
      delete :destroy, {:id => inventory_part.to_param}, valid_session
      expect(response).to redirect_to(inventory_parts_url)
    end
  end

end
